# Generated by Django 2.2 on 2020-07-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='estado',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
