# Generated by Django 2.2 on 2020-07-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_livro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
